package com.myroboot.support.controller;

import com.myroboot.support.remote.RemoteFileService;import com.myroboot.support.remote.RemoteTerminalService;import com.myroboot.support.service.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.util.*;
@RestController public class RemoteAgentController{
 private final AuthService auth;private final RemoteAgentService agents;private final RemoteTerminalService terminals;private final RemoteFileService files;
 public RemoteAgentController(AuthService a,RemoteAgentService r,RemoteTerminalService t,RemoteFileService f){auth=a;agents=r;terminals=t;files=f;}
 @GetMapping("/api/admin/remote/agents") public List<Map<String,Object>> list(@RequestHeader(value="Authorization",required=false)String a){return agents.list(admin(a));}
 @PostMapping("/api/admin/remote/agents") public Map<String,Object> create(@RequestHeader(value="Authorization",required=false)String a,@RequestBody Map<String,Object>b,HttpServletRequest r){return agents.create(admin(a),b,ip(r));}
 @PostMapping("/api/admin/remote/agents/{id}/terminal-ticket") public Map<String,Object> ticket(@RequestHeader(value="Authorization",required=false)String a,@PathVariable Long id,HttpServletRequest r){return terminals.createTicket(admin(a),id,ip(r));}
 @GetMapping("/api/admin/remote/agents/{id}/files") public Map<String,Object> fileList(@RequestHeader(value="Authorization",required=false)String a,@PathVariable Long id,@RequestParam(defaultValue="/")String path,HttpServletRequest r){return files.list(admin(a),id,path,ip(r));}
 @GetMapping("/api/admin/remote/agents/{id}/files/download") public Map<String,Object> download(@RequestHeader(value="Authorization",required=false)String a,@PathVariable Long id,@RequestParam String path,HttpServletRequest r){return files.download(admin(a),id,path,ip(r));}
 @PostMapping("/api/admin/remote/agents/{id}/files/upload") public Map<String,Object> upload(@RequestHeader(value="Authorization",required=false)String a,@PathVariable Long id,@RequestBody Map<String,Object>b,HttpServletRequest r){return files.upload(admin(a),id,String.valueOf(b.getOrDefault("path","")),String.valueOf(b.getOrDefault("data","")),Boolean.TRUE.equals(b.get("overwrite")),ip(r));}
 @PostMapping("/api/admin/remote/agents/{id}/files/mkdir") public Map<String,Object> mkdir(@RequestHeader(value="Authorization",required=false)String a,@PathVariable Long id,@RequestBody Map<String,Object>b,HttpServletRequest r){return files.mkdir(admin(a),id,String.valueOf(b.getOrDefault("path","")),ip(r));}
 @PostMapping("/api/admin/remote/agents/{id}/rotate-token") public Map<String,Object> rotate(@RequestHeader(value="Authorization",required=false)String a,@PathVariable Long id,HttpServletRequest r){return agents.rotateToken(admin(a),id,ip(r));}
 @PutMapping("/api/admin/remote/agents/{id}/enabled") public Map<String,Object> enabled(@RequestHeader(value="Authorization",required=false)String a,@PathVariable Long id,@RequestBody Map<String,Object>b,HttpServletRequest r){boolean e=Boolean.TRUE.equals(b.get("enabled"))||"true".equalsIgnoreCase(String.valueOf(b.get("enabled")))||"1".equals(String.valueOf(b.get("enabled")));agents.setEnabled(admin(a),id,e,ip(r));return Map.of("ok",true);}
 @GetMapping("/api/admin/remote/audit") public List<Map<String,Object>> audit(@RequestHeader(value="Authorization",required=false)String a,@RequestParam(defaultValue="100")int l){return agents.auditLogs(admin(a),l);}
 @PostMapping("/api/remote/agent/heartbeat") public Map<String,Object> heartbeat(@RequestHeader(value="X-Agent-Id",required=false)String id,@RequestHeader(value="X-Agent-Token",required=false)String t,@RequestBody(required=false)Map<String,Object>b){try{return agents.heartbeat(id,t,b==null?Map.of():b);}catch(SecurityException e){throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,e.getMessage());}}
 private AuthService.Session admin(String a){try{return auth.requireAdmin(a);}catch(SecurityException e){throw new ResponseStatusException(HttpStatus.FORBIDDEN,e.getMessage());}}
 private String ip(HttpServletRequest r){String f=r.getHeader("X-Forwarded-For");return f!=null&&!f.isBlank()?f.split(",")[0].trim():r.getRemoteAddr();}
}
