<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { Terminal } from '@xterm/xterm'
import { FitAddon } from '@xterm/addon-fit'
import '@xterm/xterm/css/xterm.css'
import { apiErrorMessage, showToast } from './uiFeedback'
import { copyText } from './clipboard'

const apiBase=import.meta.env.VITE_API_BASE||'/api', token=localStorage.getItem('support_token')||''
const agents=ref([]), audit=ref([]), loading=ref(false), form=ref({name:'',mineName:''}), created=ref(null)
const fileOpen=ref(false), fileAgent=ref(null), filePath=ref('/home'), fileItems=ref([]), fileLoading=ref(false), uploadInput=ref(null), transfer=ref('')
const terminalOpen=ref(false), terminalAgent=ref(null), terminalEl=ref(null)
let ws=null, terminal=null, fitAddon=null, inputDisposable=null, resizeHandler=null
const onlineCount=computed(()=>agents.value.filter(a=>Number(a.online)===1).length)
function headers(extra={}){return{...extra,Authorization:`Bearer ${token}`}}
async function request(url,options={}){options.headers=headers(options.headers||{});const r=await fetch(url,options);if(r.status===401||r.status===403)throw new Error('当前账号没有远程运维管理权限');if(!r.ok)throw new Error(await apiErrorMessage(r));return r.status===204?null:r.json()}
function time(v){return v?String(v).replace('T',' ').slice(0,19):'-'}
async function load(){loading.value=true;try{const[a,l]=await Promise.all([request(`${apiBase}/admin/remote/agents`),request(`${apiBase}/admin/remote/audit?limit=100`)]);agents.value=a;audit.value=l}catch(e){showToast(e.message)}finally{loading.value=false}}
async function createAgent(){if(!form.value.name.trim())return showToast('请填写服务器名称');try{created.value=await request(`${apiBase}/admin/remote/agents`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form.value)});form.value={name:'',mineName:''};await load();showToast('Agent 已创建，Token 只显示这一次','success')}catch(e){showToast(e.message)}}
async function rotate(a){if(!confirm(`确定重新生成 ${a.name} 的 Agent Token 吗？旧 Token 会立即失效。`))return;try{const r=await request(`${apiBase}/admin/remote/agents/${a.id}/rotate-token`,{method:'POST'});created.value={agentId:a.agent_id,token:r.token,name:a.name,mineName:a.mine_name||''};showToast('Token 已重新生成','success')}catch(e){showToast(e.message)}}
async function toggle(a){try{await request(`${apiBase}/admin/remote/agents/${a.id}/enabled`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!Boolean(Number(a.enabled))})});await load();showToast('状态已更新','success')}catch(e){showToast(e.message)}}
function installEnv(){return created.value?`MYROBOOT_SERVER=${location.origin}\nMYROBOOT_AGENT_ID=${created.value.agentId}\nMYROBOOT_AGENT_TOKEN=${created.value.token}`:''}
async function copyConfig(){try{await copyText(installEnv());showToast('Agent 配置已复制','success')}catch(e){showToast(e.message)}}

async function openFiles(a){if(Number(a.online)!==1)return showToast('Agent 当前离线');fileAgent.value=a;fileOpen.value=true;filePath.value='/home';await listFiles('/home')}
async function listFiles(path){fileLoading.value=true;try{const r=await request(`${apiBase}/admin/remote/agents/${fileAgent.value.id}/files?path=${encodeURIComponent(path)}`);filePath.value=r.path;fileItems.value=r.items||[]}catch(e){showToast(e.message)}finally{fileLoading.value=false}}
function join(name){return(filePath.value==='/'?'':filePath.value)+'/'+name}
function up(){if(['/home','/opt','/tmp','/var/log'].includes(filePath.value))return;const p=filePath.value.replace(/\/+$/,'').replace(/\/[^/]+$/,'')||'/home';listFiles(p)}
function size(n){n=Number(n||0);const units=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return`${i? n.toFixed(n<10?1:0):n} ${units[i]}`}
async function downloadFile(x){transfer.value=`正在下载 ${x.name}…`;try{const r=await request(`${apiBase}/admin/remote/agents/${fileAgent.value.id}/files/download?path=${encodeURIComponent(join(x.name))}`);const raw=atob(r.data),b=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)b[i]=raw.charCodeAt(i);const url=URL.createObjectURL(new Blob([b])),a=document.createElement('a');a.href=url;a.download=r.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast(`${x.name} 下载完成`,'success')}catch(e){showToast(e.message)}finally{transfer.value=''}}
async function uploadFiles(ev){const files=Array.from(ev?.target?.files||[]);if(!files.length)return;for(const f of files){if(f.size>50*1024*1024){showToast(`${f.name} 超过当前 50MB 限制`);continue}transfer.value=`正在上传 ${f.name}（${size(f.size)}）…`;try{const data=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=()=>no(new Error('读取本地文件失败'));r.readAsDataURL(f)});const body={path:join(f.name),data,overwrite:false};try{await request(`${apiBase}/admin/remote/agents/${fileAgent.value.id}/files/upload`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}catch(e){if(!String(e.message).includes('已存在')||!confirm(`${f.name} 已存在，是否覆盖？`))throw e;body.overwrite=true;await request(`${apiBase}/admin/remote/agents/${fileAgent.value.id}/files/upload`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}showToast(`${f.name} 上传成功`,'success')}catch(e){showToast(`${f.name}: ${e.message}`)}finally{transfer.value=''}}if(ev?.target)ev.target.value='';await listFiles(filePath.value)}
async function mkdir(){const n=prompt('新文件夹名称');if(!n)return;if(n.includes('/')||n==='.'||n==='..')return showToast('文件夹名称不合法');try{await request(`${apiBase}/admin/remote/agents/${fileAgent.value.id}/files/mkdir`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:join(n)})});await listFiles(filePath.value);showToast('文件夹已创建','success')}catch(e){showToast(e.message)}}

async function openTerminal(a){if(Number(a.online)!==1)return showToast('Agent 当前离线');closeTerminal(false);terminalAgent.value=a;terminalOpen.value=true;await nextTick();terminal=new Terminal({cursorBlink:true,fontFamily:'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace',fontSize:14,scrollback:5000,theme:{background:'#0b1220'}});fitAddon=new FitAddon();terminal.loadAddon(fitAddon);terminal.open(terminalEl.value);fitAddon.fit();terminal.focus();try{const grant=await request(`${apiBase}/admin/remote/agents/${a.id}/terminal-ticket`,{method:'POST'}),scheme=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${scheme}://${location.host}/api/remote/ws/terminal?ticket=${encodeURIComponent(grant.ticket)}`);ws.onopen=()=>{fitAddon?.fit();sendResize();inputDisposable=terminal.onData(data=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'input',data}))})};ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='terminal_output'&&m.data){const binary=atob(m.data),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));terminal?.write(new TextDecoder().decode(bytes))}else if(m.type==='terminal_error')terminal?.writeln(`\r\n[错误] ${m.message||'远程终端异常'}`);else if(m.type==='terminal_closed')terminal?.writeln('\r\n[会话已关闭]')}catch(err){terminal?.writeln(`\r\n[协议解析失败] ${err.message}`)}};ws.onerror=()=>terminal?.writeln('\r\n[连接异常] 请检查 Agent 实时通道。');ws.onclose=()=>terminal?.writeln('\r\n[连接已断开]');resizeHandler=()=>{fitAddon?.fit();sendResize()};window.addEventListener('resize',resizeHandler)}catch(e){terminal?.writeln(`\r\n[无法打开终端] ${e.message}`);showToast(e.message)}}
function sendResize(){if(ws?.readyState===WebSocket.OPEN&&terminal)ws.send(JSON.stringify({type:'resize',cols:terminal.cols,rows:terminal.rows}))}
function closeTerminal(notify=true){if(notify&&ws?.readyState===WebSocket.OPEN)try{ws.send(JSON.stringify({type:'close'}))}catch{};try{ws?.close()}catch{};ws=null;inputDisposable?.dispose();inputDisposable=null;terminal?.dispose();terminal=null;fitAddon=null;if(resizeHandler)window.removeEventListener('resize',resizeHandler);resizeHandler=null;terminalOpen.value=false;terminalAgent.value=null}
onMounted(load);onBeforeUnmount(()=>closeTerminal(false))
</script>

<template><main class="page remote-page">
<section class="admin-header"><div><span class="badge">MYROBOOT REMOTE</span><h1>远程运维中心</h1><p>Agent 身份、心跳、受控终端和安全文件管理统一入口。</p></div><div class="header-actions"><a class="back-link" href="/admin">返回管理后台</a><button class="secondary" @click="load">{{loading?'刷新中…':'刷新'}}</button></div></section>
<section class="remote-stats"><div class="panel"><small>服务器</small><strong>{{agents.length}}</strong></div><div class="panel"><small>在线</small><strong>{{onlineCount}}</strong></div><div class="panel"><small>离线 / 停用</small><strong>{{agents.length-onlineCount}}</strong></div></section>
<section class="remote-grid"><div class="panel"><div class="panel-title"><div><h2>服务器列表</h2><p class="muted">文件管理要求 Agent 0.3.0+；终端直接在当前页面打开。</p></div></div><div v-if="!agents.length" class="empty">还没有注册 Agent。</div><div class="agent-list"><article v-for="a in agents" :key="a.id" class="agent-card"><div class="agent-main"><span class="online-dot" :class="{up:Number(a.online)===1}"></span><div><strong>{{a.name}}</strong><small>{{a.mine_name||'未填写矿井'}} · {{a.hostname||'等待首次心跳'}}</small></div></div><div class="agent-meta"><span>{{a.os_name||'-'}}</span><span>Agent {{a.agent_version||'-'}}</span><span>IP {{a.private_ip||'-'}}</span><span>最后在线 {{time(a.last_seen)}}</span></div><div class="row-actions"><button class="secondary small-btn" @click="rotate(a)">重置 Token</button><button class="small-btn" :class="Number(a.enabled)===1?'danger':'success'" @click="toggle(a)">{{Number(a.enabled)===1?'停用':'启用'}}</button><button class="primary small-btn" :disabled="Number(a.online)!==1" @click="openTerminal(a)">诊断终端</button><button class="primary small-btn" :disabled="Number(a.online)!==1" @click="openFiles(a)">文件管理</button><button class="secondary small-btn" disabled>桌面（开发中）</button></div></article></div></div>
<div class="panel create-agent"><h2>新增被控端</h2><label>服务器名称<input v-model="form.name" placeholder="例如：骆驼山前置机"></label><label>矿井名称<input v-model="form.mineName" placeholder="例如：骆驼山煤矿"></label><button class="primary" @click="createAgent">生成 Agent 身份</button><div v-if="created" class="token-box"><strong>{{created.name}} 的一次性配置</strong><p>Token 不会再次明文显示，部署完成后请妥善保存。</p><textarea :value="installEnv()" readonly rows="6"></textarea><button class="secondary" @click="copyConfig">复制配置</button></div></div></section>
<section class="panel audit-panel"><div class="panel-title"><div><h2>远程运维审计</h2><p class="muted">记录 Agent、终端会话和文件操作路径；不记录终端输入和文件内容。</p></div></div><div class="table-wrap"><table><thead><tr><th>时间</th><th>服务器</th><th>操作人</th><th>动作</th><th>详情</th><th>来源 IP</th></tr></thead><tbody><tr v-for="l in audit" :key="l.id"><td>{{time(l.create_time)}}</td><td>{{l.agent_name||'-'}}</td><td>{{l.operator_name||'-'}}</td><td>{{l.action_type}}</td><td>{{l.detail||'-'}}</td><td>{{l.client_ip||'-'}}</td></tr></tbody></table></div></section>
<div v-if="terminalOpen" class="overlay" @click.self="closeTerminal()"><section class="terminal-dialog"><header class="dark-head"><div><strong>{{terminalAgent?.name}} · 诊断终端</strong><small>受控诊断命令；终端输入不落审计日志</small></div><button class="secondary small-btn" @click="closeTerminal()">关闭</button></header><div ref="terminalEl" class="terminal-screen"></div></section></div>
<div v-if="fileOpen" class="overlay" @click.self="fileOpen=false"><section class="files"><header><div><strong>{{fileAgent?.name}} · 文件管理</strong><code>{{filePath}}</code></div><div><button @click="up">上一级</button><button @click="listFiles('/home')">/home</button><button @click="listFiles('/opt')">/opt</button><button @click="listFiles('/tmp')">/tmp</button><button @click="listFiles('/var/log')">/var/log</button><button @click="mkdir">新建文件夹</button><button class="primary" @click="uploadInput?.click()">上传</button><button @click="fileOpen=false">关闭</button><input ref="uploadInput" type="file" multiple hidden @change="uploadFiles"></div></header><div class="security-note">安全范围：读取 /home、/opt、/tmp、/var/log；写入仅 /home、/opt、/tmp。当前单文件 ≤ 50MB。</div><div v-if="transfer" class="transfer">{{transfer}}</div><div class="drop" @dragover.prevent @drop.prevent="uploadFiles({target:{files:$event.dataTransfer.files,value:''}})">拖拽文件到这里上传</div><table><thead><tr><th>名称</th><th>大小</th><th>权限</th><th>修改时间</th><th></th></tr></thead><tbody><tr v-if="fileLoading"><td colspan="5">读取中…</td></tr><tr v-for="x in fileItems" :key="x.name"><td><button class="link" @click="x.dir&&listFiles(join(x.name))">{{x.dir?'📁':'📄'}} {{x.name}}</button></td><td>{{x.dir?'-':size(x.size)}}</td><td><code>{{x.mode}}</code></td><td>{{time(x.modified)}}</td><td><button v-if="!x.dir" @click="downloadFile(x)">下载</button></td></tr></tbody></table></section></div>
</main></template>
<style scoped>.remote-page{display:grid;gap:20px}.remote-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.remote-stats .panel{display:grid;gap:6px}.remote-stats strong{font-size:30px}.remote-grid{display:grid;grid-template-columns:1.5fr .7fr;gap:20px}.agent-list{display:grid;gap:12px}.agent-card{border:1px solid #e3e9f1;border-radius:14px;padding:16px;display:grid;gap:13px}.agent-main{display:flex;gap:10px;align-items:center}.agent-main>div{display:grid}.agent-main small,.agent-meta{color:#7d8da4;font-size:13px}.online-dot{width:10px;height:10px;border-radius:50%;background:#a8b2c0}.online-dot.up{background:#1d9b63}.agent-meta{display:flex;gap:16px;flex-wrap:wrap}.create-agent{display:grid;gap:15px;align-content:start}.token-box{border:1px solid #f1d28b;background:#fffaf0;border-radius:12px;padding:14px;display:grid;gap:10px}.token-box textarea{width:100%;font-family:monospace}.audit-panel table{min-width:900px}.overlay{position:fixed;inset:0;background:rgba(5,12,24,.68);z-index:1000;padding:28px;display:grid;place-items:center}.terminal-dialog{width:min(1280px,96vw);height:min(820px,90vh);background:#0b1220;border-radius:16px;overflow:hidden;display:grid;grid-template-rows:auto 1fr}.dark-head{background:#111c2f;color:#fff;padding:13px 16px;display:flex;justify-content:space-between}.dark-head>div{display:grid}.dark-head small{color:#91a1b8}.terminal-screen{min-height:0;padding:10px}.terminal-screen :deep(.xterm){height:100%}.files{background:#fff;width:min(1250px,96vw);height:min(850px,92vh);border-radius:16px;padding:18px;overflow:auto}.files>header{display:flex;justify-content:space-between;gap:15px;align-items:center}.files>header>div{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.security-note,.transfer{margin-top:12px;padding:10px 12px;border-radius:9px;background:#f5f7fa;color:#536277}.transfer{background:#eef6ff}.drop{margin:12px 0;padding:22px;border:2px dashed #ccd5e0;border-radius:12px;text-align:center;color:#64748b}.files table{width:100%}.files th,.files td{text-align:left;padding:9px;border-bottom:1px solid #edf0f4}.link{border:0;background:none;cursor:pointer;text-align:left}@media(max-width:900px){.remote-stats,.remote-grid{grid-template-columns:1fr}.agent-meta{display:grid;gap:5px}.overlay{padding:8px}.files>header{display:grid}.terminal-dialog{width:100%;height:94vh}}
</style>
