<script setup>
import {onMounted,ref} from 'vue'
import {apiErrorMessage,showToast} from './uiFeedback'
const apiBase=import.meta.env.VITE_API_BASE||'/api',token=localStorage.getItem('support_token')||'';const items=ref([]),loading=ref(false)
function headers(extra={}){return{...extra,Authorization:`Bearer ${token}`}}async function request(url,o={}){o.headers=headers(o.headers||{});const r=await fetch(url,o);if(r.status===401){localStorage.clear();location.href='/';throw new Error('登录已失效')}if(!r.ok)throw new Error(await apiErrorMessage(r));return r.json()}
async function load(){loading.value=true;try{items.value=await request(`${apiBase}/admin/knowledge-permission/requests`)}catch(e){showToast(e.message)}finally{loading.value=false}}
async function review(x,approve){if(!confirm(`确定${approve?'同意':'拒绝'} ${x.display_name||x.username} 的问题库录入权限申请吗？`))return;try{await request(`${apiBase}/admin/knowledge-permission/requests/${x.id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approve})});showToast(approve?'已授权问题库录入权限':'已拒绝申请','success');await load()}catch(e){showToast(e.message)}}
function time(v){return v?String(v).replace('T',' ').slice(0,19):'-'}onMounted(load)
</script>
<template><main class="page"><header><div><span>MYROBOOT ADMIN</span><h1>问题库权限审批</h1><p>处理人员只有在管理员明确授权后，才能新增问题库内容。</p></div><a href="/admin">返回管理后台</a></header><section class="panel"><div class="title"><h2>权限申请</h2><span>{{items.filter(x=>x.status==='pending').length}} 个待审批</span></div><p v-if="!items.length&&!loading" class="empty">暂无权限申请。</p><article v-for="x in items" :key="x.id" :class="x.status"><div><b>{{x.display_name||x.username}}</b><small>{{x.username}} · {{x.company_name||'-'}} · {{x.email||'-'}}</small><p>{{x.reason||'未填写申请说明'}}</p><small>申请时间 {{time(x.create_time)}}</small></div><div class="right"><span>{{x.status==='pending'?'待审批':x.status==='approved'?'已同意':'已拒绝'}}</span><div v-if="x.status==='pending'"><button class="approve" @click="review(x,true)">同意</button><button class="reject" @click="review(x,false)">拒绝</button></div></div></article></section></main></template>
<style scoped>.page{max-width:1200px;margin:auto;padding:34px 22px;background:#f4f7fb;min-height:100vh}header{display:flex;justify-content:space-between;align-items:center;background:#10243e;color:white;padding:28px;border-radius:20px}header h1{margin:7px 0}header p{margin:0;color:#c6d2e1}header a{color:white}.panel{margin-top:16px;background:white;border:1px solid #e0e7ef;border-radius:18px;padding:22px}.title{display:flex;justify-content:space-between}.panel article{display:flex;justify-content:space-between;gap:20px;padding:18px 0;border-top:1px solid #edf1f5}.panel article>div:first-child{display:grid;gap:6px}.panel small{color:#8190a3}.panel p{margin:4px 0}.right{display:grid;justify-items:end;gap:10px}.right button{border:0;border-radius:8px;padding:9px 13px;margin-left:8px}.approve{background:#16794a;color:#fff}.reject{background:#fff0f0;color:#b42318}.approved{opacity:.7}.rejected{opacity:.6}.empty{text-align:center;color:#8190a3;padding:30px}@media(max-width:700px){header,.panel article{display:grid}.right{justify-items:start}.right button{margin:0 8px 0 0}}</style>