<script setup>
import { onMounted, ref } from 'vue'
const apiBase=import.meta.env.VITE_API_BASE||'/api'; const token=localStorage.getItem('support_token')||''
const users=ref([]); const editing=ref(null); const form=ref({username:'',email:'',password:'',displayName:'',companyName:'',mineName:'',phone:'',role:'customer',enabled:true}); const error=ref('')
function headers(){return {'Content-Type':'application/json',Authorization:`Bearer ${token}`}}
async function load(){const r=await fetch(`${apiBase}/admin/users`,{headers:{Authorization:`Bearer ${token}`}}); if(!r.ok) throw new Error('加载用户失败'); users.value=await r.json()}
function reset(){editing.value=null; form.value={username:'',email:'',password:'',displayName:'',companyName:'',mineName:'',phone:'',role:'customer',enabled:true}}
function edit(u){editing.value=u.id; form.value={username:u.username,email:u.email||'',password:'',displayName:u.display_name||'',companyName:u.company_name||'',mineName:u.mine_name||'',phone:u.phone||'',role:u.role||'customer',enabled:u.enabled===1||u.enabled===true}}
async function save(){error.value=''; try{const r=await fetch(editing.value?`${apiBase}/admin/users/${editing.value}`:`${apiBase}/admin/users`,{method:editing.value?'PUT':'POST',headers:headers(),body:JSON.stringify(form.value)}); const t=await r.text(); if(!r.ok) throw new Error(t||'保存失败'); reset(); await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><main class="page"><header><div><span>MYROBOOT ADMIN</span><h1>用户维护</h1><p>单个新增、修改客户或管理员账号。批量账号仍可在主后台通过 Excel 导入。</p></div><a href="/admin">返回管理后台</a></header><section class="layout"><div class="panel"><h2>{{editing?'编辑用户':'新增用户'}}</h2><div class="grid"><label>用户名<input v-model="form.username" /></label><label>邮箱<input v-model="form.email" type="email" /></label><label>姓名<input v-model="form.displayName" /></label><label>手机号<input v-model="form.phone" /></label><label>单位<input v-model="form.companyName" /></label><label>矿井<input v-model="form.mineName" /></label><label>{{editing?'新密码（留空不修改）':'初始密码'}}<input v-model="form.password" type="password" /></label><label>角色<select v-model="form.role"><option value="customer">客户</option><option value="admin">管理员</option></select></label></div><label class="check"><input v-model="form.enabled" type="checkbox"/> 启用账号</label><div v-if="error" class="error">{{error}}</div><div class="actions"><button class="primary" @click="save">保存</button><button v-if="editing" @click="reset">取消</button></div></div><div class="panel list"><h2>现有用户</h2><table><thead><tr><th>账号</th><th>邮箱</th><th>姓名</th><th>单位/矿井</th><th>角色</th><th></th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td>{{u.username}}</td><td>{{u.email||'-'}}</td><td>{{u.display_name||'-'}}</td><td>{{u.company_name||'-'}}<br/><small>{{u.mine_name||'-'}}</small></td><td>{{u.role}}</td><td><button @click="edit(u)">编辑</button></td></tr></tbody></table></div></section></main></template>
<style scoped>.page{max-width:1200px;margin:auto;padding:36px 22px;background:#f4f7fb;min-height:100vh}header{background:#10243e;color:#fff;border-radius:22px;padding:30px;display:flex;justify-content:space-between;align-items:center}header span{font-size:12px;letter-spacing:1.4px;opacity:.7}header h1{margin:8px 0}header p{color:#c8d4e3}header a{color:#fff;text-decoration:none;border:1px solid #ffffff40;padding:10px 14px;border-radius:9px}.layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:18px;margin-top:18px}.panel{background:#fff;border:1px solid #e3e9f1;border-radius:16px;padding:22px;overflow:auto}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid label{display:grid;gap:7px;font-weight:600}.grid input,.grid select{border:1px solid #d8e0eb;border-radius:9px;padding:10px}.check{display:flex;gap:8px;margin-top:15px}.actions{display:flex;gap:9px;margin-top:18px}.actions button,td button{border:0;border-radius:8px;padding:9px 13px}.primary{background:#245eea;color:#fff}.error{margin-top:12px;color:#b42318;background:#fff1f0;padding:10px;border-radius:8px}table{width:100%;border-collapse:collapse;min-width:650px}th,td{text-align:left;padding:11px;border-top:1px solid #edf1f5}th{color:#718096;font-size:13px}@media(max-width:800px){.layout,.grid{grid-template-columns:1fr}header{display:block}header a{display:inline-block;margin-top:10px}}</style>
