<script setup>
import { nextTick,onMounted,ref } from 'vue'
import Quill from 'quill'
import 'quill/dist/quill.snow.css'
import { apiErrorMessage,showToast } from './uiFeedback'
const apiBase=import.meta.env.VITE_API_BASE||'/api';const token=localStorage.getItem('support_token')||''
const items=ref([]),editing=ref(null),uploading=ref(false),editor=ref(null);let quill=null
const form=ref({category:'',question:'',answer:'',keywords:'',enabled:true,images:[],attachments:[]})
function headers(extra={}){return {...extra,Authorization:`Bearer ${token}`}}
async function req(url,opt={}){opt.headers=headers(opt.headers||{});const r=await fetch(url,opt);if(!r.ok)throw new Error(await apiErrorMessage(r));return r.status===204?null:r.json()}
async function load(){items.value=await req(`${apiBase}/admin/faqs`)}
function init(){nextTick(()=>{if(!editor.value)return;if(!quill){quill=new Quill(editor.value,{theme:'snow',modules:{toolbar:[[{header:[1,2,3,false]}],['bold','italic','underline','strike'],[{color:[]},{background:[]}],[{list:'ordered'},{list:'bullet'}],[{align:[]}],['blockquote','code-block','link'],['clean']]}});quill.on('text-change',()=>form.value.answer=quill.root.innerHTML)}quill.root.innerHTML=form.value.answer||''})}
function reset(){editing.value=null;form.value={category:'',question:'',answer:'',keywords:'',enabled:true,images:[],attachments:[]};if(quill)quill.root.innerHTML=''}
function edit(x){editing.value=x.id;form.value={category:x.category,question:x.question,answer:x.answer,keywords:x.keywords||'',enabled:x.enabled===1||x.enabled===true,images:[...(x.images||[])],attachments:(x.attachments||[]).map(a=>({url:a.file_url,name:a.original_name,contentType:a.content_type,size:a.file_size}))};init()}
async function upload(event,target,image=false){const files=Array.from(event.target.files||[]);if(!files.length)return;uploading.value=true;try{for(const file of files){const fd=new FormData();fd.append('file',file);const data=await req(`${apiBase}/upload/${image?'image':'attachment'}`,{method:'POST',body:fd});target.push(image?data.url:data)}}catch(e){showToast(e.message)}finally{uploading.value=false;event.target.value=''}}
function remove(target,i){target.splice(i,1)}
function size(v){const n=Number(v||0);return n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}
function video(f){return String(f.contentType||'').startsWith('video/')||/\.(mp4|mov|avi|mkv|webm)$/i.test(f.name||'')}
async function save(){form.value.answer=quill?.root.innerHTML||form.value.answer;if(!form.value.category.trim()||!form.value.question.trim()||!form.value.answer.trim())return showToast('分类、问题标题、解决方案都必须填写');try{await req(editing.value?`${apiBase}/admin/faqs/${editing.value}`:`${apiBase}/admin/faqs`,{method:editing.value?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form.value)});showToast('问题库已保存','success');reset();await load()}catch(e){showToast(e.message)}}
async function del(x){if(!confirm(`确定删除“${x.question}”吗？`))return;await req(`${apiBase}/admin/faqs/${x.id}`,{method:'DELETE'});await load()}
onMounted(async()=>{await load();init()})
</script>
<template><main class="page"><header><div><span>MYROBOOT ADMIN</span><h1>高级问题库管理</h1><p>富文本、图片、文档、Excel、压缩包和视频统一维护。</p></div><a href="/admin">返回管理后台</a></header><section class="layout"><div class="panel list"><div class="title"><h2>问题库</h2><button @click="reset">新增问题</button></div><article v-for="x in items" :key="x.id"><div><small>{{x.category}}</small><strong>{{x.question}}</strong><em>{{x.attachments?.length||0}} 个附件 · {{x.images?.length||0}} 张图</em></div><div><button @click="edit(x)">编辑</button><button class="danger" @click="del(x)">删除</button></div></article></div><div class="panel editor"><h2>{{editing?'编辑问题':'新增问题'}}</h2><label>分类<input v-model="form.category"/></label><label>问题标题<input v-model="form.question"/></label><label>搜索关键词<input v-model="form.keywords"/></label><label>解决方案</label><div ref="editor" class="quill"></div><label>图片<input type="file" multiple accept="image/*" @change="upload($event,form.images,true)"/></label><div class="images"><div v-for="(img,i) in form.images" :key="img"><img :src="img"/><button @click="remove(form.images,i)">×</button></div></div><label>相关资料 / 附件<input type="file" multiple @change="upload($event,form.attachments,false)"/><small>支持 Excel、Word、PPT、PDF、日志、压缩包及 MP4/MOV/AVI/MKV/WebM 视频。普通文件≤30MB，视频≤200MB。</small></label><div class="files"><div v-for="(f,i) in form.attachments" :key="f.url"><video v-if="video(f)" :src="f.url" controls preload="metadata"></video><span><strong>{{f.name}}</strong><small>{{size(f.size)}}</small></span><button @click="remove(form.attachments,i)">移除</button></div></div><label class="check"><input v-model="form.enabled" type="checkbox"/> 启用并展示给客户</label><button class="primary" :disabled="uploading" @click="save">{{uploading?'文件上传中...':'保存问题库'}}</button></div></section></main></template>
<style scoped>.page{max-width:1250px;margin:auto;padding:32px 22px 70px;background:#f4f7fb;min-height:100vh}header{background:#10243e;color:#fff;border-radius:22px;padding:30px;display:flex;justify-content:space-between;align-items:center}header span{font-size:12px;letter-spacing:1.4px;opacity:.7}header h1{margin:8px 0}header p{color:#c8d4e3;margin:0}header a{color:#fff;text-decoration:none;border:1px solid #ffffff40;padding:10px 14px;border-radius:9px}.layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:18px;margin-top:18px}.panel{background:#fff;border:1px solid #e3e9f1;border-radius:16px;padding:22px}.title{display:flex;justify-content:space-between;align-items:center}.list article{display:flex;justify-content:space-between;gap:14px;padding:14px 0;border-top:1px solid #edf1f5}.list article>div:first-child{display:grid;gap:5px}.list small{color:#245eea}.list em{font-style:normal;color:#8391a3;font-size:12px}.list button,.editor button{border:0;border-radius:8px;padding:8px 12px}.danger{background:#fff0f0;color:#b42318;margin-left:6px}.editor{display:grid;gap:13px}.editor label{display:grid;gap:7px;font-weight:600}.editor input{border:1px solid #d8e0eb;border-radius:9px;padding:10px}.quill{min-height:280px}.images{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.images>div{position:relative}.images img{width:100%;height:110px;object-fit:cover;border-radius:9px}.images button{position:absolute;right:5px;top:5px}.files{display:grid;gap:8px}.files>div{border:1px solid #e2e8f0;border-radius:10px;padding:10px;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.files video{grid-column:1/-1;width:100%;max-height:320px;background:#111;border-radius:8px}.files span{display:grid}.files small{color:#8391a3}.check{display:flex!important;align-items:center}.check input{width:auto}.primary{background:#245eea;color:#fff;padding:12px!important}@media(max-width:850px){.layout{grid-template-columns:1fr}header{display:block}header a{display:inline-block;margin-top:12px}}
</style>