<script setup>
import { nextTick,onMounted,ref,watch } from 'vue'
import Quill from 'quill'
import 'quill/dist/quill.snow.css'
import { apiErrorMessage,showToast } from './uiFeedback'
const apiBase=import.meta.env.VITE_API_BASE||'/api',token=localStorage.getItem('support_token')||''
const faqs=ref([]),permission=ref({granted:false,latestRequest:{}}),reason=ref(''),requesting=ref(false),saving=ref(false),uploading=ref(false),editorEl=ref(null);let quill=null
const form=ref({category:'',question:'',answer:'',keywords:'',enabled:true,images:[],attachments:[]})
function headers(extra={}){return{...extra,Authorization:`Bearer ${token}`}}async function request(url,options={}){options.headers=headers(options.headers||{});const r=await fetch(url,options);if(r.status===401){localStorage.clear();location.href='/';throw new Error('登录已失效，请重新登录')}if(!r.ok)throw new Error(await apiErrorMessage(r));return r.status===204?null:r.json()}
function initEditor(){nextTick(()=>{if(!editorEl.value||quill)return;quill=new Quill(editorEl.value,{theme:'snow',placeholder:'写清楚现象、原因、处理步骤、注意事项……'});quill.on('text-change',()=>form.value.answer=quill.root.innerHTML)})}
async function load(){try{[faqs.value,permission.value]=await Promise.all([request(`${apiBase}/faq`),request(`${apiBase}/processor/knowledge-permission`)])}catch(e){showToast(e.message)}}
async function apply(){requesting.value=true;try{await request(`${apiBase}/processor/knowledge-permission/requests`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:reason.value})});showToast('申请已提交，管理员已收到审批通知','success');await load()}catch(e){showToast(e.message)}finally{requesting.value=false}}
async function uploadFiles(e){const files=Array.from(e.target.files||[]);if(form.value.attachments.length+files.length>20)return showToast('一个问题最多上传 20 个附件');uploading.value=true;try{for(const file of files){const fd=new FormData();fd.append('file',file);const d=await request(`${apiBase}/upload/attachment`,{method:'POST',body:fd});form.value.attachments.push(d)}}catch(err){showToast(err.message)}finally{uploading.value=false;e.target.value=''}}
async function save(){form.value.answer=quill?.root.innerHTML||'';if(!form.value.category.trim()||!form.value.question.trim()||!form.value.answer||form.value.answer==='<p><br></p>')return showToast('请完整填写分类、标题和解决方案');saving.value=true;try{const d=await request(`${apiBase}/processor/faqs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form.value)});showToast(`问题 #${d.id} 已录入问题库`,'success');form.value={category:'',question:'',answer:'',keywords:'',enabled:true,images:[],attachments:[]};quill?.setText('');await load()}catch(e){showToast(e.message)}finally{saving.value=false}}
watch(()=>permission.value.granted,v=>{if(v)initEditor()})
onMounted(load)
</script>
<template><section class="knowledge-layout"><div class="panel"><div class="title"><div><h2>问题库</h2><p>查看现有标准方案，避免重复录入。</p></div><span>{{faqs.length}} 条</span></div><article v-for="x in faqs" :key="x.id" class="faq"><span>{{x.category}}</span><b>{{x.question}}</b></article></div><div class="panel editor-panel"><template v-if="!permission.granted"><h2>问题库录入权限</h2><div v-if="permission.latestRequest?.status==='pending'" class="notice"><b>申请审批中</b><p>管理员已经收到审批通知。审批通过前，你仍然可以处理工单和查看问题库，但不能新增问题。</p></div><template v-else><p>处理人员默认没有问题库写入权限。需要录入标准方案时，请向管理员申请。</p><label>申请说明<textarea v-model="reason" maxlength="500" placeholder="例如：负责视频平台问题处理，需要沉淀常见故障解决方案"></textarea></label><button class="primary" :disabled="requesting" @click="apply">{{requesting?'提交中…':'申请录入权限'}}</button><p v-if="permission.latestRequest?.status==='rejected'" class="rejected">上一次申请未通过，你可以补充说明后重新申请。</p></template></template><template v-else><div class="approved"><b>问题库录入权限已授权</b><span>你可以新增经过验证的解决方案；修改和删除仍由管理员负责。</span></div><label>分类 *<input v-model="form.category"/></label><label>问题标题 *<input v-model="form.question"/></label><label>解决方案 *</label><div ref="editorEl" class="editor"></div><label>搜索关键词<input v-model="form.keywords"/></label><label class="upload">{{uploading?'上传中…':'选择附件'}}<input type="file" multiple @change="uploadFiles"/></label><div v-for="(f,i) in form.attachments" :key="f.url" class="file"><span>{{f.name}}</span><button @click="form.attachments.splice(i,1)">移除</button></div><button class="primary" :disabled="saving||uploading" @click="save">{{saving?'保存中…':'录入问题库'}}</button></template></div></section></template>
<style scoped>.knowledge-layout{display:grid;grid-template-columns:.85fr 1.15fr;gap:16px}.panel{background:#fff;border:1px solid #e0e7ef;border-radius:18px;padding:22px}.title{display:flex;justify-content:space-between}.title h2{margin:0}.title p,.editor-panel p{color:#7c8999}.faq{display:flex;gap:10px;padding:14px 0;border-top:1px solid #edf1f5}.faq span{color:#245eea}.editor-panel{display:grid;gap:14px}label{display:grid;gap:7px;font-weight:600}input,textarea{border:1px solid #d7dfeb;border-radius:9px;padding:11px}textarea{min-height:110px}.editor{min-height:260px}.primary{border:0;background:#245eea;color:#fff;border-radius:9px;padding:11px 15px;width:max-content}.notice,.approved{padding:16px;border-radius:12px;background:#f1f6ff;border:1px solid #cfddf7}.approved{display:grid;gap:5px}.approved span{color:#617187}.rejected{color:#b42318!important}.upload{width:max-content;background:#eef4ff;color:#245eea;padding:10px 13px;border-radius:9px}.upload input{display:none}.file{display:flex;justify-content:space-between;padding:8px;border:1px solid #e5eaf0;border-radius:8px}@media(max-width:900px){.knowledge-layout{grid-template-columns:1fr}}</style>