<script setup>
import { computed,onMounted,ref } from 'vue'
const apiBase=import.meta.env.VITE_API_BASE||'/api'; const token=localStorage.getItem('support_token')||''; const role=localStorage.getItem('support_role')||''
const id=new URLSearchParams(location.search).get('id'); const admin=computed(()=>role==='admin'); const ticket=ref(null); const history=ref([]); const note=ref(''); const visible=ref(true); const reason=ref(''); const result=ref(''); const error=ref('')
function auth(extra={}){return {...extra,Authorization:`Bearer ${token}`}}
async function json(url,options={}){options.headers=auth(options.headers||{}); const r=await fetch(url,options); const t=await r.text(); if(!r.ok) throw new Error(t||'请求失败'); return t?JSON.parse(t):null}
async function load(){try{const list=await json(admin.value?`${apiBase}/admin/tickets`:`${apiBase}/tickets/mine`); ticket.value=list.find(x=>String(x.id)===String(id))||null; history.value=await json(`${apiBase}/tickets/${id}/history`); if(ticket.value){reason.value=ticket.value.resolution_reason||'';result.value=ticket.value.resolution_result||''}}catch(e){error.value=e.message}}
async function add(){if(!note.value.trim()) return; await json(`${apiBase}/admin/tickets/${id}/history`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:note.value,visibleToCustomer:visible.value})}); note.value=''; await load()}
async function resolve(){if(!reason.value.trim()||!result.value.trim()) return alert('请填写原因和处理结果'); await json(`${apiBase}/admin/tickets/${id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resolutionReason:reason.value,resolutionResult:result.value})}); await load()}
function actionText(v){return {progress:'处理记录',resolved:'已解决',created:'已提交'}[v]||v}
function time(v){return v?String(v).replace('T',' ').slice(0,19):'-'}
onMounted(load)
</script>
<template><main class="page"><header><div><span>MYROBOOT SUPPORT</span><h1>工单 #{{id}} 处理详情</h1></div><a :href="admin?'/admin':'/'">返回</a></header><div v-if="error" class="error">{{error}}</div><section v-if="ticket" class="panel"><div class="head"><div><b>{{ticket.category||'技术问题'}}</b><small>{{time(ticket.create_time)}}</small></div><strong>{{ticket.status}}</strong></div><p class="desc">{{ticket.description}}</p><img v-if="ticket.screenshot_url" :src="ticket.screenshot_url" class="shot"/></section><section class="panel"><h2>处理时间线</h2><div v-if="!history.length" class="empty">暂无处理记录</div><div v-for="item in history" :key="item.id" class="timeline"><i></i><div><div class="meta"><b>{{actionText(item.action_type)}}</b><span>{{item.operator_name||'系统'}} · {{time(item.create_time)}}</span></div><p>{{item.content}}</p><small v-if="admin&&item.visible_to_customer===0">仅管理员可见</small></div></div></section><template v-if="admin"><section class="panel"><h2>新增处理记录</h2><textarea v-model="note" rows="5" placeholder="记录排查过程、客户配合事项、当前进展"></textarea><label class="check"><input v-model="visible" type="checkbox"/> 对客户可见</label><button @click="add">保存处理记录</button></section><section class="panel"><h2>解决回执</h2><label>具体原因<textarea v-model="reason" rows="4"/></label><label>处理结果<textarea v-model="result" rows="5"/></label><button class="primary" @click="resolve">保存并标记已解决</button></section></template></main></template>
<style scoped>.page{max-width:900px;margin:auto;padding:34px 20px 70px;background:#f4f7fb;min-height:100vh}header{background:#10243e;color:#fff;border-radius:20px;padding:28px;display:flex;justify-content:space-between;align-items:center}header span{font-size:12px;letter-spacing:1.4px;opacity:.7}header h1{margin:8px 0}header a{color:#fff;text-decoration:none;border:1px solid #ffffff40;padding:9px 13px;border-radius:8px}.panel{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:22px;margin-top:16px}.head{display:flex;justify-content:space-between}.head small{display:block;color:#8391a3;margin-top:5px}.desc{white-space:pre-wrap;line-height:1.7}.shot{max-width:320px;max-height:240px;border-radius:10px;border:1px solid #e5eaf0}.timeline{display:grid;grid-template-columns:18px 1fr;gap:12px;padding:12px 0}.timeline i{width:10px;height:10px;border-radius:50%;background:#245eea;margin-top:6px;box-shadow:0 0 0 5px #edf3ff}.timeline>div{border-bottom:1px solid #eef2f6;padding-bottom:14px}.meta{display:flex;justify-content:space-between;gap:15px}.meta span{color:#8795a7;font-size:13px}.timeline p{white-space:pre-wrap;line-height:1.7}.timeline small{color:#a16a00}textarea{width:100%;border:1px solid #d7dfeb;border-radius:9px;padding:11px;box-sizing:border-box;margin:8px 0 12px}label{display:grid;gap:6px;margin-top:12px}.check{display:flex;align-items:center;gap:8px}button{border:0;border-radius:9px;padding:10px 15px;background:#eef2f7}.primary{background:#245eea;color:#fff}.error{margin-top:16px;padding:12px;background:#fff1f0;color:#b42318;border-radius:9px}.empty{color:#8795a7}</style>
