package com.myroboot.support.service;

import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.mail.SimpleMailMessage;import org.springframework.mail.javamail.JavaMailSender;import org.springframework.scheduling.annotation.Async;import org.springframework.stereotype.Service;
import java.sql.Timestamp;import java.time.LocalDateTime;import java.util.*;

@Service
public class MaintenanceNoticeService {
 private static final Logger log=LoggerFactory.getLogger(MaintenanceNoticeService.class);private final JdbcTemplate jdbc;private final JavaMailSender mail;
 @Value("${support.mail.from:}") String from;@Value("${spring.mail.username:}") String username;
 public MaintenanceNoticeService(JdbcTemplate j,JavaMailSender m){jdbc=j;mail=m;}
 public List<Map<String,Object>> list(){return jdbc.queryForList("SELECT n.*,u.display_name creator_name FROM maintenance_notice n LEFT JOIN support_user u ON u.id=n.created_by ORDER BY n.id DESC LIMIT 100");}
 public Map<String,Object> preview(){Integer n=jdbc.queryForObject("SELECT COUNT(DISTINCT LOWER(TRIM(email))) FROM support_user WHERE enabled=1 AND email IS NOT NULL AND TRIM(email)<>''",Integer.class);return Map.of("recipientCount",n==null?0:n);}
 public long create(AuthService.Session admin,Map<String,Object>b){String title=text(b.get("title")),content=text(b.get("content")),type=text(b.get("noticeType"));if(title.isBlank()||title.length()>200)throw new IllegalArgumentException("维护标题必填且不能超过 200 字");if(content.isBlank()||content.length()>10000)throw new IllegalArgumentException("维护说明必填且不能超过 10000 字");if(type.isBlank())type="maintenance";if(!Set.of("maintenance","completed").contains(type))throw new IllegalArgumentException("通知类型无效");LocalDateTime start=parse(b.get("startTime")),end=parse(b.get("endTime"));if(start!=null&&end!=null&&!end.isAfter(start))throw new IllegalArgumentException("预计结束时间必须晚于开始时间");jdbc.update("INSERT INTO maintenance_notice(title,notice_type,start_time,end_time,impact_scope,content,status,created_by) VALUES (?,?,?,?,?,?,'draft',?)",title,type,ts(start),ts(end),shorten(text(b.get("impactScope")),500),content,admin.userId());return Objects.requireNonNull(jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class));}
 public void send(AuthService.Session admin,long id,boolean retryFailed){Map<String,Object> n=one(id);String status=text(n.get("status"));if(!retryFailed&&!"draft".equals(status))throw new IllegalArgumentException("该通知已经发送或正在发送");if(retryFailed&&!Set.of("partial_failed","failed").contains(status))throw new IllegalArgumentException("当前没有可重试的失败邮件");if(!retryFailed){jdbc.update("INSERT IGNORE INTO maintenance_notice_recipient(notice_id,user_id,recipient_email) SELECT ?,MIN(id),LOWER(TRIM(email)) FROM support_user WHERE enabled=1 AND email IS NOT NULL AND TRIM(email)<>'' GROUP BY LOWER(TRIM(email))",id);Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM maintenance_notice_recipient WHERE notice_id=?",Integer.class,id);if(total==null||total==0)throw new IllegalArgumentException("没有可发送的有效用户邮箱");jdbc.update("UPDATE maintenance_notice SET status='sending',total_count=?,sent_count=0,failed_count=0,send_started_time=NOW(),send_finished_time=NULL WHERE id=?",total,id);}else jdbc.update("UPDATE maintenance_notice SET status='sending',send_finished_time=NULL WHERE id=?",id);dispatch(id,retryFailed);}
 @Async public void dispatch(long id,boolean retryFailed){Map<String,Object> n=one(id);String where=retryFailed?"status='failed'":"status='pending'";List<Map<String,Object>> rs=jdbc.queryForList("SELECT id,recipient_email FROM maintenance_notice_recipient WHERE notice_id=? AND "+where+" ORDER BY id",id);for(Map<String,Object>r:rs){long rid=((Number)r.get("id")).longValue();String email=text(r.get("recipient_email"));int claimed=jdbc.update("UPDATE maintenance_notice_recipient SET status='sending',attempt_count=attempt_count+1,last_error=NULL WHERE id=? AND status IN ('pending','failed')",rid);if(claimed==0)continue;try{SimpleMailMessage m=new SimpleMailMessage();String sender=from==null||from.isBlank()?username:from;if(sender!=null&&!sender.isBlank())m.setFrom(sender);m.setTo(email);m.setSubject("[MYROBOOT] "+text(n.get("title")));m.setText(body(n));mail.send(m);jdbc.update("UPDATE maintenance_notice_recipient SET status='sent',sent_time=NOW(),last_error=NULL WHERE id=?",rid);log.info("MAINTENANCE_MAIL_SENT noticeId={} emailDomain={}",id,domain(email));}catch(Exception e){String err=shorten(root(e),1000);jdbc.update("UPDATE maintenance_notice_recipient SET status='failed',last_error=? WHERE id=?",err,rid);log.warn("MAINTENANCE_MAIL_FAILED noticeId={} emailDomain={} reason={}",id,domain(email),err);}}
  Integer sent=jdbc.queryForObject("SELECT COUNT(*) FROM maintenance_notice_recipient WHERE notice_id=? AND status='sent'",Integer.class,id),failed=jdbc.queryForObject("SELECT COUNT(*) FROM maintenance_notice_recipient WHERE notice_id=? AND status='failed'",Integer.class,id);String finalStatus=(failed!=null&&failed>0)?((sent!=null&&sent>0)?"partial_failed":"failed"):"sent";jdbc.update("UPDATE maintenance_notice SET status=?,sent_count=?,failed_count=?,send_finished_time=NOW() WHERE id=?",finalStatus,sent==null?0:sent,failed==null?0:failed,id);
 }
 public List<Map<String,Object>> recipients(long id){return jdbc.queryForList("SELECT r.id,r.user_id,r.status,r.attempt_count,r.last_error,r.sent_time,r.create_time,u.display_name,u.username FROM maintenance_notice_recipient r LEFT JOIN support_user u ON u.id=r.user_id WHERE r.notice_id=? ORDER BY r.id",id);}
 private Map<String,Object> one(long id){List<Map<String,Object>>r=jdbc.queryForList("SELECT * FROM maintenance_notice WHERE id=? LIMIT 1",id);if(r.isEmpty())throw new IllegalArgumentException("维护通知不存在");return r.get(0);}private String body(Map<String,Object>n){StringBuilder b=new StringBuilder("各位用户，您好：\n\n").append(text(n.get("content"))).append("\n\n");if(n.get("start_time")!=null)b.append("维护开始：").append(n.get("start_time")).append("\n");if(n.get("end_time")!=null)b.append("预计结束：").append(n.get("end_time")).append("\n");if(!text(n.get("impact_scope")).isBlank())b.append("影响范围：").append(text(n.get("impact_scope"))).append("\n");return b.append("\n请提前保存正在处理的内容。维护完成后请重新访问系统。\n\nMYROBOOT 技术支持平台").toString();}
 private LocalDateTime parse(Object v){String s=text(v);if(s.isBlank())return null;try{return LocalDateTime.parse(s);}catch(Exception e){throw new IllegalArgumentException("时间格式不正确");}}private Timestamp ts(LocalDateTime t){return t==null?null:Timestamp.valueOf(t);}private String text(Object v){return v==null?"":String.valueOf(v).trim();}private String shorten(String s,int n){return s==null?"":s.length()<=n?s:s.substring(0,n);}private String root(Throwable e){while(e.getCause()!=null)e=e.getCause();return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}private String domain(String e){int i=e.indexOf('@');return i<0?"unknown":e.substring(i+1);}
}
